import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/errors/failure.dart';
import '../models/enrichment_result.dart';
import '../models/flash_card.dart';
import '../models/translation_result.dart';
import '../models/word_input.dart';
import '../modules/cards/card_provider.dart';
import '../modules/enrichment/enrichment_provider.dart';
import '../modules/enrichment/gemini_enrichment_service.dart';
import '../modules/translation/translation_provider.dart';

/// Combined state for the Translate screen.
/// Holds both translation + enrichment results and the save state.
class TranslatePipelineState {
  final bool isTranslating;
  final bool isEnriching;
  final TranslationResult? translation;
  final EnrichmentResult? enrichment;
  final Failure? failure;
  final bool isSaved;
  final WordInput? lastInput;

  const TranslatePipelineState({
    this.isTranslating  = false,
    this.isEnriching    = false,
    this.translation,
    this.enrichment,
    this.failure,
    this.isSaved        = false,
    this.lastInput,
  });

  bool get isLoading => isTranslating || isEnriching;
  bool get hasResult => translation != null;

  TranslatePipelineState copyWith({
    bool? isTranslating,
    bool? isEnriching,
    TranslationResult? translation,
    EnrichmentResult? enrichment,
    Failure? failure,
    bool? clearFailure,
    bool? isSaved,
    WordInput? lastInput,
  }) =>
      TranslatePipelineState(
        isTranslating: isTranslating ?? this.isTranslating,
        isEnriching:   isEnriching   ?? this.isEnriching,
        translation:   translation   ?? this.translation,
        enrichment:    enrichment    ?? this.enrichment,
        failure:       clearFailure == true ? null : failure ?? this.failure,
        isSaved:       isSaved      ?? this.isSaved,
        lastInput:     lastInput    ?? this.lastInput,
      );
}

/// Orchestrates the full translate → enrich pipeline.
///
/// This is the ONLY place where TranslationService and EnrichmentService
/// interact. Neither module is aware of the other.
///
/// Pipeline:
///   1. translate(WordInput) via ITranslationService (DeepL)
///   2. enrich concurrently using translation context (Gemini)
///   3. Combine into TranslatePipelineState
///   4. saveCard() → ICardRepository.saveCard()
class TranslatePipelineNotifier extends StateNotifier<TranslatePipelineState> {
  final Ref _ref;

  TranslatePipelineNotifier(this._ref)
      : super(const TranslatePipelineState());

  Future<void> translate(WordInput input) async {
    state = TranslatePipelineState(
      isTranslating: true,
      lastInput: input,
    );

    // ── Step 1: Translation ────────────────────────────────────────────────
    final TranslationResult translationResult;
    try {
      translationResult = await _ref
          .read(translationServiceProvider)
          .translate(input);
    } catch (e) {
      state = TranslatePipelineState(
        failure: _toFailure(e),
        lastInput: input,
      );
      return;
    }

    // Update state with translation while enrichment loads
    state = state.copyWith(
      isTranslating: false,
      isEnriching: true,
      translation: translationResult,
    );

    // ── Step 2: Enrichment (with full context — matches Next.js behavior) ──
    EnrichmentResult? enrichmentResult;
    try {
      final geminiService = _ref.read(enrichmentServiceProvider) as GeminiEnrichmentService;
      enrichmentResult = await geminiService.enrichWithTranslation(
        word:       translationResult.original,
        translation:translationResult.translation,
        sourceLang: translationResult.sourceLang,
        targetLang: translationResult.targetLang,
      );
    } catch (_) {
      // Enrichment failure is non-fatal — translation result is still useful
      enrichmentResult = null;
    }

    state = state.copyWith(
      isEnriching: false,
      enrichment: enrichmentResult,
    );
  }

  /// Save the current result as a FlashCard for [userId].
  Future<void> saveCard(String userId) async {
    final t = state.translation;
    final e = state.enrichment;
    if (t == null) return;

    try {
      final card = FlashCard(
        id:              '',       // generated by Supabase
        userId:          userId,
        word:            t.original,
        translation:     t.translation,
        transcription:   e?.transcription,
        exampleSentence: e?.exampleSentence,
        synonyms:        e?.synonyms,
        usageNotes:      e?.usageNotes,
        status:          CardStatus.learning,
        nextReview:      DateTime.now(),
        createdAt:       DateTime.now(),
      );
      await _ref.read(cardListProvider.notifier).saveCard(card);
      state = state.copyWith(isSaved: true);
    } catch (e) {
      state = state.copyWith(failure: DatabaseFailure(e.toString()));
    }
  }

  void reset() => state = const TranslatePipelineState();

  Failure _toFailure(Object e) {
    final msg = e.toString();
    if (msg.contains('quota'))   return const TranslationFailure('DeepL quota exceeded');
    if (msg.contains('API key')) return const TranslationFailure('Invalid DeepL API key');
    if (msg.contains('internet') || msg.contains('connection')) {
      return const NetworkFailure();
    }
    return TranslationFailure(msg);
  }
}

final translatePipelineProvider = StateNotifierProvider.autoDispose<
    TranslatePipelineNotifier, TranslatePipelineState>(
  (ref) => TranslatePipelineNotifier(ref),
);
