import 'dart:async';

import 'package:flutter/material.dart';
import '../core/constants/app_colors.dart';
import '../core/theme/app_theme.dart';

/// Tappable emoji button that toggles [InlineEmojiPicker] visibility.
class EmojiPickerField extends StatelessWidget {
  final String emoji;
  final VoidCallback onTap;
  final bool isExpanded;
  final double size;
  final double fontSize;

  const EmojiPickerField({
    super.key,
    required this.emoji,
    required this.onTap,
    this.isExpanded = false,
    this.size = 52,
    this.fontSize = 26,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        width: size,
        height: size,
        decoration: BoxDecoration(
          color: AppColors.surface2,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(
            color: isExpanded
                ? AppColors.accent.withOpacity(0.5)
                : AppColors.surface3.withOpacity(0.4),
          ),
        ),
        child: Center(
          child: Text(emoji, style: AppTheme.emojiStyle.copyWith(fontSize: fontSize)),
        ),
      ),
    );
  }
}

/// Inline scrollable emoji picker with category tabs and search.
class InlineEmojiPicker extends StatefulWidget {
  final String selected;
  final ValueChanged<String> onPicked;
  final double height;

  const InlineEmojiPicker({
    super.key,
    required this.selected,
    required this.onPicked,
    this.height = 220,
  });

  @override
  State<InlineEmojiPicker> createState() => _InlineEmojiPickerState();
}

class _InlineEmojiPickerState extends State<InlineEmojiPicker> {
  int _categoryIndex = 0;
  String _search = '';
  List<String>? _cachedSearchResults;
  final _searchCtrl = TextEditingController();
  final _searchFocus = FocusNode();
  Timer? _searchDebounce;
  bool _gridReady = false;

  @override
  void initState() {
    super.initState();
    // Defer the emoji grid by one frame so the picker container appears
    // instantly and the grid fills in without blocking the animation.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) setState(() => _gridReady = true);
    });
  }

  @override
  void dispose() {
    _searchDebounce?.cancel();
    _searchCtrl.dispose();
    _searchFocus.dispose();
    super.dispose();
  }

  void _onSearchChanged(String value) {
    _searchDebounce?.cancel();
    final trimmed = value.trim();
    if (trimmed.isEmpty) {
      setState(() {
        _search = '';
        _cachedSearchResults = null;
      });
      return;
    }
    _searchDebounce = Timer(const Duration(milliseconds: 200), () {
      if (!mounted) return;
      setState(() {
        _search = trimmed;
        _cachedSearchResults = null; // invalidate cache
      });
    });
  }

  List<String> get _filteredEmojis {
    if (_search.isEmpty) return _categories[_categoryIndex].emojis;
    if (_cachedSearchResults != null) return _cachedSearchResults!;
    final q = _search.toLowerCase();
    final results = <String>[];
    for (final cat in _categories) {
      for (final e in cat.emojis) {
        final keywords = _emojiKeywords[e];
        if (keywords != null && keywords.any((k) => k.contains(q))) {
          results.add(e);
        }
      }
    }
    _cachedSearchResults = results;
    return results;
  }

  @override
  Widget build(BuildContext context) {
    final emojis = _filteredEmojis;
    return Container(
      height: widget.height,
      decoration: BoxDecoration(
        color: AppColors.surface2,
        borderRadius: BorderRadius.circular(14),
      ),
      child: Column(
        children: [
          // Search bar
          Padding(
            padding: const EdgeInsets.fromLTRB(8, 8, 8, 4),
            child: SizedBox(
              height: 34,
              child: TextField(
                controller: _searchCtrl,
                focusNode: _searchFocus,
                onChanged: _onSearchChanged,
                style: const TextStyle(
                    fontSize: 13, color: AppColors.text),
                decoration: InputDecoration(
                  hintText: 'Search emoji...',
                  hintStyle: const TextStyle(
                      color: AppColors.textDim, fontSize: 13),
                  prefixIcon: const Icon(Icons.search_rounded,
                      size: 18, color: AppColors.textDim),
                  prefixIconConstraints:
                      const BoxConstraints(minWidth: 34),
                  suffixIcon: _search.isNotEmpty
                      ? GestureDetector(
                          onTap: () {
                            _searchCtrl.clear();
                            setState(() => _search = '');
                          },
                          child: const Icon(Icons.close_rounded,
                              size: 16, color: AppColors.textDim),
                        )
                      : null,
                  suffixIconConstraints:
                      const BoxConstraints(minWidth: 30),
                  filled: true,
                  fillColor: AppColors.surface,
                  contentPadding: const EdgeInsets.symmetric(
                      horizontal: 8, vertical: 0),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(10),
                    borderSide: BorderSide.none,
                  ),
                ),
              ),
            ),
          ),
          // Category tabs (hidden during search)
          if (_search.isEmpty)
            SizedBox(
              height: 36,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                padding:
                    const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                itemCount: _categories.length,
                itemBuilder: (_, i) {
                  final isActive = i == _categoryIndex;
                  return GestureDetector(
                    onTap: () => setState(() => _categoryIndex = i),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 150),
                      margin: const EdgeInsets.symmetric(horizontal: 2),
                      padding: const EdgeInsets.symmetric(horizontal: 10),
                      decoration: BoxDecoration(
                        color: isActive
                            ? AppColors.accent.withOpacity(0.15)
                            : Colors.transparent,
                        borderRadius: BorderRadius.circular(10),
                      ),
                      alignment: Alignment.center,
                      child: Text(
                        _categories[i].icon,
                        style: AppTheme.emojiStyle.copyWith(fontSize: 18),
                      ),
                    ),
                  );
                },
              ),
            ),
          Container(
            height: 0.5,
            color: AppColors.surface3.withOpacity(0.5),
          ),
          // Emoji grid — deferred by one frame to avoid jank on open
          Expanded(
            child: !_gridReady
                ? const SizedBox.shrink()
                : emojis.isEmpty
                ? Center(
                    child: Text(
                      'No emoji found',
                      style: TextStyle(
                          color: AppColors.textDim, fontSize: 13),
                    ),
                  )
                : GridView.builder(
                    padding: const EdgeInsets.all(6),
                    gridDelegate:
                        const SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 8,
                      mainAxisSpacing: 2,
                      crossAxisSpacing: 2,
                    ),
                    itemCount: emojis.length,
                    itemBuilder: (_, i) {
                      final e = emojis[i];
                      final isSelected = e == widget.selected;
                      return GestureDetector(
                        onTap: () => widget.onPicked(e),
                        child: Container(
                          decoration: BoxDecoration(
                            color: isSelected
                                ? AppColors.accent.withOpacity(0.2)
                                : Colors.transparent,
                            borderRadius: BorderRadius.circular(8),
                            border: isSelected
                                ? Border.all(
                                    color:
                                        AppColors.accent.withOpacity(0.5))
                                : null,
                          ),
                          alignment: Alignment.center,
                          child:
                              Text(e, style: AppTheme.emojiStyle.copyWith(fontSize: 22)),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }

  static const _categories = <_EmojiCategory>[
    _EmojiCategory('😀', 'Smileys', [
      '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃',
      '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '😚', '😙',
      '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫',
      '🤔', '🫡', '🤐', '🤨', '😐', '😑', '😶', '🫥', '😏', '😒',
      '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '😴', '😷', '🤒',
      '🤕', '🤢', '🤮', '🥵', '🥶', '🥴', '😵', '🤯', '🤠', '🥳',
      '🥸', '😎', '🤓', '🧐', '😕', '🫤', '😟', '🙁', '😮', '😯',
      '😲', '😳', '🥺', '🥹', '😦', '😧', '😨', '😰', '😥', '😢',
      '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫', '🥱', '😤',
      '😡', '😠', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹',
      '👻', '👽', '👾', '🤖', '🎃', '😺', '😸', '😹', '😻', '😼',
    ]),
    _EmojiCategory('👋', 'Hands', [
      '👋', '🤚', '🖐️', '✋', '🖖', '🫱', '🫲', '🫳', '🫴', '👌',
      '🤌', '🤏', '✌️', '🤞', '🫰', '🤟', '🤘', '🤙', '👈', '👉',
      '👆', '🖕', '👇', '☝️', '🫵', '👍', '👎', '✊', '👊', '🤛',
      '🤜', '👏', '🙌', '🫶', '👐', '🤲', '🤝', '🙏', '✍️', '💅',
      '🤳', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻', '👃', '🧠',
      '👀', '👁️', '👅', '👄', '🫦', '💋', '👶', '🧒', '👦', '👧',
    ]),
    _EmojiCategory('🐶', 'Animals', [
      '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐻‍❄️', '🐨',
      '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒',
      '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇',
      '🐺', '🐗', '🐴', '🦄', '🐝', '🪱', '🐛', '🦋', '🐌', '🐞',
      '🐜', '🪰', '🪲', '🪳', '🦟', '🦗', '🕷️', '🦂', '🐢', '🐍',
      '🦎', '🦖', '🦕', '🐙', '🦑', '🪼', '🦐', '🦞', '🦀', '🐡',
      '🐠', '🐟', '🐬', '🐳', '🐋', '🦈', '🪸', '🐊', '🐅', '🐆',
      '🦓', '🫏', '🦍', '🦧', '🦣', '🐘', '🦛', '🦏', '🐪', '🐫',
    ]),
    _EmojiCategory('🍔', 'Food', [
      '🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐',
      '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅', '🍆', '🥑',
      '🥦', '🫛', '🥬', '🥒', '🌶️', '🫑', '🌽', '🥕', '🫒', '🧄',
      '🧅', '🥔', '🍠', '🫘', '🥐', '🥖', '🫓', '🍞', '🥨', '🥯',
      '🧇', '🥞', '🍳', '🥚', '🧀', '🥩', '🥓', '🍔', '🍟', '🍕',
      '🌭', '🥪', '🌮', '🌯', '🫔', '🥙', '🧆', '🥗', '🍝', '🍜',
      '🍲', '🍛', '🍣', '🍱', '🥟', '🦪', '🍤', '🍙', '🍚', '🍘',
      '🍥', '🥠', '🥮', '🍡', '🥧', '🍰', '🎂', '🍮', '🍭', '🍬',
      '🍫', '🍿', '🍩', '🍪', '☕', '🍵', '🫖', '🧋', '🥤', '🍺',
    ]),
    _EmojiCategory('⚽', 'Activities', [
      '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱',
      '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳',
      '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛼', '🛷',
      '⛸️', '🥌', '🎿', '⛷️', '🏂', '🪂', '🏋️', '🤸', '🤺', '⛹️',
      '🤾', '🏌️', '🏇', '🧘', '🏄', '🏊', '🤽', '🚣', '🧗', '🚴',
      '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏵️', '🎗️', '🎪', '🎭',
      '🎨', '🎬', '🎤', '🎧', '🎼', '🎹', '🥁', '🪘', '🎷', '🎺',
      '🪗', '🎸', '🎻', '🪕', '🎲', '♟️', '🎯', '🎳', '🎮', '🕹️',
    ]),
    _EmojiCategory('✈️', 'Travel', [
      '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐',
      '🛻', '🚚', '🚛', '🚜', '🛵', '🏍️', '🛺', '🚲', '🛴', '🚏',
      '🛣️', '🛤️', '⛽', '🛞', '🚨', '🚥', '🚦', '🚧', '⚓', '🛟',
      '⛵', '🚤', '🛳️', '⛴️', '🛥️', '🚢', '✈️', '🛩️', '🛫', '🛬',
      '🪂', '💺', '🚁', '🚟', '🚠', '🚡', '🛰️', '🚀', '🛸', '🌍',
      '🌎', '🌏', '🗺️', '🧭', '🏔️', '⛰️', '🌋', '🗻', '🏕️', '🏖️',
      '🏜️', '🏝️', '🏞️', '🏟️', '🏛️', '🏗️', '🧱', '🪨', '🪵', '🛖',
      '🏠', '🏡', '🏢', '🏣', '🏤', '🏥', '🏦', '🏨', '🏩', '🏪',
    ]),
    _EmojiCategory('💡', 'Objects', [
      '💡', '🔦', '🕯️', '📚', '📖', '📝', '✏️', '🖊️', '🖋️', '📌',
      '📎', '🔗', '📐', '📏', '🗂️', '📁', '📂', '🗃️', '📦', '📫',
      '📮', '📯', '📰', '🗞️', '💰', '💳', '💎', '⚖️', '🪜', '🧰',
      '🪛', '🔧', '🔨', '⚒️', '🛠️', '⛏️', '🪚', '🔩', '⚙️', '🪤',
      '🧲', '🔫', '💣', '🪓', '🗡️', '⚔️', '🛡️', '🔮', '🪄', '🎩',
      '📱', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '💾', '💿', '📀', '🎥',
      '📷', '📸', '📹', '📺', '📻', '🎙️', '🎚️', '🎛️', '⏱️', '⏰',
      '🔑', '🗝️', '🔒', '🔓', '❤️', '🧡', '💛', '💚', '💙', '💜',
    ]),
    _EmojiCategory('🏳️', 'Symbols', [
      '⭐', '🌟', '✨', '💫', '🔥', '💥', '⚡', '🌈', '☀️', '🌤️',
      '⛅', '🌥️', '🌦️', '🌧️', '⛈️', '🌩️', '🌪️', '🌫️', '🌊', '💧',
      '❄️', '☃️', '⛄', '🎄', '🎆', '🎇', '🧨', '🎈', '🎉', '🎊',
      '🎋', '🎍', '🎎', '🎏', '🎐', '🎑', '🧧', '🎀', '🎁', '🎗️',
      '✅', '❌', '❓', '❗', '‼️', '⁉️', '💯', '🔴', '🟠', '🟡',
      '🟢', '🔵', '🟣', '⚫', '⚪', '🟤', '🔶', '🔷', '🔸', '🔹',
      '♠️', '♥️', '♦️', '♣️', '🃏', '🀄', '🎴', '🔇', '🔈', '🔉',
      '🔊', '📢', '📣', '🔔', '🔕', '🎵', '🎶', '🏴', '🏁', '🚩',
    ]),
  ];

  // Keyword map for search
  static final _emojiKeywords = <String, List<String>>{
    // Smileys
    '😀': ['grin', 'happy', 'smile', 'face'],
    '😃': ['happy', 'smile', 'open', 'face'],
    '😄': ['happy', 'smile', 'laugh', 'face'],
    '😁': ['grin', 'beam', 'happy', 'smile'],
    '😆': ['laugh', 'happy', 'squint', 'face'],
    '😅': ['sweat', 'smile', 'nervous', 'relief'],
    '🤣': ['rofl', 'laugh', 'lol', 'funny'],
    '😂': ['joy', 'laugh', 'cry', 'tears', 'funny', 'lol'],
    '🙂': ['smile', 'slight', 'face'],
    '🙃': ['upside', 'down', 'silly', 'sarcasm'],
    '😉': ['wink', 'face'],
    '😊': ['blush', 'smile', 'happy', 'shy'],
    '😇': ['angel', 'halo', 'innocent', 'face'],
    '🥰': ['love', 'hearts', 'adore', 'face'],
    '😍': ['love', 'heart', 'eyes', 'crush'],
    '🤩': ['star', 'struck', 'excited', 'wow'],
    '😘': ['kiss', 'love', 'heart', 'blow'],
    '😗': ['kiss', 'face'],
    '😚': ['kiss', 'blush', 'face'],
    '😙': ['kiss', 'smile', 'face'],
    '🥲': ['smile', 'tear', 'sad', 'happy'],
    '😋': ['yummy', 'delicious', 'tongue', 'food'],
    '😛': ['tongue', 'playful', 'silly'],
    '😜': ['wink', 'tongue', 'crazy', 'silly'],
    '🤪': ['crazy', 'wild', 'zany', 'silly'],
    '😝': ['tongue', 'squint', 'silly', 'playful'],
    '🤑': ['money', 'rich', 'dollar', 'cash'],
    '🤗': ['hug', 'warm', 'embrace'],
    '🤭': ['giggle', 'oops', 'cover', 'mouth'],
    '🤫': ['shush', 'quiet', 'secret', 'silence'],
    '🤔': ['think', 'hmm', 'wonder', 'question'],
    '🫡': ['salute', 'respect', 'honor'],
    '🤐': ['zip', 'mouth', 'secret', 'quiet'],
    '🤨': ['raised', 'eyebrow', 'skeptical', 'doubt'],
    '😐': ['neutral', 'face', 'blank', 'meh'],
    '😑': ['expressionless', 'blank', 'face'],
    '😶': ['silent', 'mute', 'speechless'],
    '🫥': ['dotted', 'hidden', 'invisible'],
    '😏': ['smirk', 'flirt', 'sly'],
    '😒': ['unamused', 'bored', 'meh', 'annoyed'],
    '🙄': ['eye', 'roll', 'annoyed', 'whatever'],
    '😬': ['grimace', 'awkward', 'cringe'],
    '🤥': ['lie', 'pinocchio', 'nose'],
    '😌': ['relieved', 'peaceful', 'calm'],
    '😔': ['sad', 'pensive', 'down'],
    '😪': ['sleepy', 'tired', 'tear'],
    '🤤': ['drool', 'hungry', 'yum'],
    '😴': ['sleep', 'zzz', 'tired', 'nap'],
    '😷': ['mask', 'sick', 'medical', 'covid'],
    '🤒': ['sick', 'thermometer', 'fever', 'ill'],
    '🤕': ['hurt', 'bandage', 'injured'],
    '🤢': ['nausea', 'sick', 'green', 'ill'],
    '🤮': ['vomit', 'sick', 'puke'],
    '🥵': ['hot', 'heat', 'sweat', 'warm'],
    '🥶': ['cold', 'freeze', 'ice', 'frozen'],
    '🥴': ['woozy', 'drunk', 'dizzy'],
    '😵': ['dizzy', 'dead', 'spiral'],
    '🤯': ['mind', 'blown', 'explode', 'shock'],
    '🤠': ['cowboy', 'hat', 'western'],
    '🥳': ['party', 'celebrate', 'birthday', 'fun'],
    '🥸': ['disguise', 'glasses', 'nose', 'mustache'],
    '😎': ['cool', 'sunglasses', 'awesome'],
    '🤓': ['nerd', 'geek', 'glasses', 'smart'],
    '🧐': ['monocle', 'inspect', 'smart', 'curious'],
    '😕': ['confused', 'face'],
    '🫤': ['diagonal', 'mouth', 'skeptical'],
    '😟': ['worried', 'concern', 'face'],
    '🙁': ['frown', 'sad', 'face'],
    '😮': ['open', 'mouth', 'surprised', 'wow'],
    '😯': ['hushed', 'surprised', 'stunned'],
    '😲': ['astonished', 'shocked', 'surprised'],
    '😳': ['flushed', 'embarrassed', 'blush'],
    '🥺': ['pleading', 'puppy', 'eyes', 'please'],
    '🥹': ['hold', 'tears', 'moved', 'touched'],
    '😦': ['frown', 'open', 'mouth'],
    '😧': ['anguish', 'face'],
    '😨': ['fear', 'scared', 'afraid'],
    '😰': ['anxious', 'sweat', 'nervous'],
    '😥': ['sad', 'relieved', 'sweat'],
    '😢': ['cry', 'sad', 'tear'],
    '😭': ['sob', 'cry', 'loud', 'sad', 'tears'],
    '😱': ['scream', 'horror', 'fear', 'shock'],
    '😖': ['confounded', 'face'],
    '😣': ['persevere', 'struggle', 'face'],
    '😞': ['disappointed', 'sad', 'face'],
    '😓': ['sweat', 'hard', 'work'],
    '😩': ['weary', 'tired', 'face'],
    '😫': ['tired', 'exhausted', 'face'],
    '🥱': ['yawn', 'bored', 'tired', 'sleepy'],
    '😤': ['angry', 'triumph', 'huff', 'steam'],
    '😡': ['angry', 'mad', 'rage', 'red'],
    '😠': ['angry', 'mad', 'face'],
    '🤬': ['swear', 'curse', 'angry', 'symbols'],
    '😈': ['devil', 'evil', 'horns', 'smile'],
    '👿': ['devil', 'angry', 'evil', 'imp'],
    '💀': ['skull', 'dead', 'death', 'skeleton'],
    '☠️': ['skull', 'crossbones', 'death', 'danger'],
    '💩': ['poop', 'poo', 'shit'],
    '🤡': ['clown', 'face', 'circus'],
    '👹': ['ogre', 'monster', 'demon', 'japanese'],
    '👻': ['ghost', 'boo', 'halloween', 'spooky'],
    '👽': ['alien', 'ufo', 'space', 'extraterrestrial'],
    '👾': ['alien', 'monster', 'game', 'space', 'invader'],
    '🤖': ['robot', 'bot', 'machine', 'android'],
    '🎃': ['pumpkin', 'halloween', 'jack', 'lantern'],
    '😺': ['cat', 'smile', 'happy'],
    '😸': ['cat', 'grin', 'happy'],
    '😹': ['cat', 'joy', 'tears', 'laugh'],
    '😻': ['cat', 'love', 'heart', 'eyes'],
    '😼': ['cat', 'smirk', 'wry'],
    // Hands
    '👋': ['wave', 'hello', 'hi', 'bye', 'hand'],
    '🤚': ['raised', 'back', 'hand', 'stop'],
    '🖐️': ['hand', 'fingers', 'five', 'splayed'],
    '✋': ['hand', 'stop', 'high', 'five'],
    '🖖': ['vulcan', 'spock', 'star', 'trek'],
    '🫱': ['right', 'hand'],
    '🫲': ['left', 'hand'],
    '🫳': ['palm', 'down', 'hand'],
    '🫴': ['palm', 'up', 'hand'],
    '👌': ['ok', 'perfect', 'fine', 'hand'],
    '🤌': ['pinch', 'italian', 'chef', 'kiss'],
    '🤏': ['pinch', 'small', 'tiny', 'little'],
    '✌️': ['peace', 'victory', 'two', 'hand'],
    '🤞': ['cross', 'fingers', 'luck', 'hope'],
    '🫰': ['hand', 'index', 'thumb'],
    '🤟': ['love', 'you', 'hand', 'rock'],
    '🤘': ['rock', 'metal', 'horns', 'hand'],
    '🤙': ['call', 'phone', 'shaka', 'hang', 'loose'],
    '👈': ['point', 'left', 'hand'],
    '👉': ['point', 'right', 'hand'],
    '👆': ['point', 'up', 'hand'],
    '🖕': ['middle', 'finger'],
    '👇': ['point', 'down', 'hand'],
    '☝️': ['point', 'up', 'index', 'hand'],
    '🫵': ['point', 'you', 'hand'],
    '👍': ['thumbs', 'up', 'like', 'good', 'yes'],
    '👎': ['thumbs', 'down', 'dislike', 'bad', 'no'],
    '✊': ['fist', 'punch', 'power'],
    '👊': ['fist', 'bump', 'punch'],
    '🤛': ['fist', 'left'],
    '🤜': ['fist', 'right'],
    '👏': ['clap', 'applause', 'bravo'],
    '🙌': ['raise', 'hands', 'hooray', 'celebrate'],
    '🫶': ['heart', 'hands', 'love'],
    '👐': ['open', 'hands'],
    '🤲': ['palms', 'up', 'hands'],
    '🤝': ['handshake', 'deal', 'agree'],
    '🙏': ['pray', 'please', 'thanks', 'namaste', 'hope'],
    '✍️': ['write', 'writing', 'hand', 'pen'],
    '💅': ['nail', 'polish', 'beauty', 'manicure'],
    '🤳': ['selfie', 'phone', 'camera'],
    '💪': ['muscle', 'strong', 'arm', 'flex', 'power'],
    '🦾': ['mechanical', 'arm', 'robot', 'prosthetic'],
    '🦿': ['mechanical', 'leg', 'robot', 'prosthetic'],
    '🦵': ['leg', 'kick'],
    '🦶': ['foot', 'kick', 'stomp'],
    '👂': ['ear', 'listen', 'hear'],
    '🦻': ['ear', 'hearing', 'aid'],
    '👃': ['nose', 'smell'],
    '🧠': ['brain', 'smart', 'think', 'mind', 'intelligent'],
    '👀': ['eyes', 'look', 'see', 'watch'],
    '👁️': ['eye', 'see', 'watch'],
    '👅': ['tongue', 'taste', 'lick'],
    '👄': ['lips', 'mouth', 'kiss'],
    '🫦': ['lip', 'bite', 'nervous'],
    '💋': ['kiss', 'lips', 'love', 'mark'],
    '👶': ['baby', 'child', 'infant'],
    '🧒': ['child', 'kid'],
    '👦': ['boy', 'child', 'kid'],
    '👧': ['girl', 'child', 'kid'],
    // Animals
    '🐶': ['dog', 'puppy', 'pet', 'animal'],
    '🐱': ['cat', 'kitten', 'pet', 'animal'],
    '🐭': ['mouse', 'animal'],
    '🐹': ['hamster', 'pet', 'animal'],
    '🐰': ['rabbit', 'bunny', 'pet', 'animal'],
    '🦊': ['fox', 'animal'],
    '🐻': ['bear', 'animal'],
    '🐼': ['panda', 'bear', 'animal'],
    '🐻‍❄️': ['polar', 'bear', 'ice', 'arctic'],
    '🐨': ['koala', 'animal'],
    '🐯': ['tiger', 'animal', 'cat'],
    '🦁': ['lion', 'king', 'animal', 'cat'],
    '🐮': ['cow', 'animal'],
    '🐷': ['pig', 'animal'],
    '🐸': ['frog', 'toad', 'animal'],
    '🐵': ['monkey', 'animal', 'ape'],
    '🙈': ['monkey', 'see', 'no', 'evil'],
    '🙉': ['monkey', 'hear', 'no', 'evil'],
    '🙊': ['monkey', 'speak', 'no', 'evil'],
    '🐒': ['monkey', 'animal'],
    '🐔': ['chicken', 'hen', 'bird'],
    '🐧': ['penguin', 'bird', 'animal'],
    '🐦': ['bird', 'animal'],
    '🐤': ['chick', 'bird', 'baby'],
    '🐣': ['chick', 'hatch', 'bird', 'baby'],
    '🐥': ['chick', 'bird', 'baby'],
    '🦆': ['duck', 'bird', 'animal'],
    '🦅': ['eagle', 'bird', 'america'],
    '🦉': ['owl', 'bird', 'wise', 'night'],
    '🦇': ['bat', 'vampire', 'animal'],
    '🐺': ['wolf', 'animal'],
    '🐗': ['boar', 'pig', 'animal'],
    '🐴': ['horse', 'animal'],
    '🦄': ['unicorn', 'horse', 'magic', 'fantasy'],
    '🐝': ['bee', 'honey', 'insect'],
    '🪱': ['worm', 'insect'],
    '🐛': ['bug', 'caterpillar', 'insect'],
    '🦋': ['butterfly', 'insect', 'beautiful'],
    '🐌': ['snail', 'slow'],
    '🐞': ['ladybug', 'insect', 'beetle'],
    '🐜': ['ant', 'insect'],
    '🪰': ['fly', 'insect'],
    '🪲': ['beetle', 'insect', 'bug'],
    '🪳': ['cockroach', 'insect', 'bug'],
    '🦟': ['mosquito', 'insect', 'bug'],
    '🦗': ['cricket', 'insect'],
    '🕷️': ['spider', 'web', 'insect'],
    '🦂': ['scorpion', 'animal'],
    '🐢': ['turtle', 'tortoise', 'slow', 'animal'],
    '🐍': ['snake', 'reptile', 'animal'],
    '🦎': ['lizard', 'reptile', 'animal'],
    '🦖': ['dinosaur', 'trex', 'animal'],
    '🦕': ['dinosaur', 'sauropod', 'animal'],
    '🐙': ['octopus', 'sea', 'animal'],
    '🦑': ['squid', 'sea', 'animal'],
    '🪼': ['jellyfish', 'sea', 'animal'],
    '🦐': ['shrimp', 'seafood', 'animal'],
    '🦞': ['lobster', 'seafood', 'animal'],
    '🦀': ['crab', 'seafood', 'animal'],
    '🐡': ['blowfish', 'fish', 'sea'],
    '🐠': ['fish', 'tropical', 'sea'],
    '🐟': ['fish', 'sea', 'animal'],
    '🐬': ['dolphin', 'sea', 'animal'],
    '🐳': ['whale', 'sea', 'animal', 'spout'],
    '🐋': ['whale', 'sea', 'animal'],
    '🦈': ['shark', 'sea', 'fish', 'danger'],
    '🪸': ['coral', 'sea', 'reef'],
    '🐊': ['crocodile', 'alligator', 'reptile'],
    '🐅': ['tiger', 'animal'],
    '🐆': ['leopard', 'animal', 'cat'],
    '🦓': ['zebra', 'animal', 'stripes'],
    '🫏': ['donkey', 'animal'],
    '🦍': ['gorilla', 'ape', 'animal'],
    '🦧': ['orangutan', 'ape', 'animal'],
    '🦣': ['mammoth', 'animal', 'extinct'],
    '🐘': ['elephant', 'animal', 'big'],
    '🦛': ['hippo', 'hippopotamus', 'animal'],
    '🦏': ['rhino', 'rhinoceros', 'animal'],
    '🐪': ['camel', 'animal', 'desert'],
    '🐫': ['camel', 'animal', 'desert', 'two', 'humps'],
    // Food
    '🍏': ['apple', 'green', 'fruit'],
    '🍎': ['apple', 'red', 'fruit'],
    '🍐': ['pear', 'fruit'],
    '🍊': ['orange', 'tangerine', 'fruit'],
    '🍋': ['lemon', 'citrus', 'fruit'],
    '🍌': ['banana', 'fruit'],
    '🍉': ['watermelon', 'fruit', 'summer'],
    '🍇': ['grape', 'grapes', 'fruit', 'wine'],
    '🍓': ['strawberry', 'fruit', 'berry'],
    '🫐': ['blueberry', 'fruit', 'berry'],
    '🍈': ['melon', 'fruit'],
    '🍒': ['cherry', 'fruit'],
    '🍑': ['peach', 'fruit'],
    '🥭': ['mango', 'fruit', 'tropical'],
    '🍍': ['pineapple', 'fruit', 'tropical'],
    '🥥': ['coconut', 'tropical'],
    '🥝': ['kiwi', 'fruit'],
    '🍅': ['tomato', 'vegetable'],
    '🍆': ['eggplant', 'aubergine', 'vegetable'],
    '🥑': ['avocado', 'vegetable', 'guacamole'],
    '🥦': ['broccoli', 'vegetable'],
    '🫛': ['pea', 'pod', 'vegetable'],
    '🥬': ['leafy', 'green', 'vegetable', 'lettuce'],
    '🥒': ['cucumber', 'vegetable'],
    '🌶️': ['pepper', 'hot', 'chili', 'spicy'],
    '🫑': ['pepper', 'bell', 'vegetable'],
    '🌽': ['corn', 'vegetable', 'maize'],
    '🥕': ['carrot', 'vegetable'],
    '🫒': ['olive', 'food'],
    '🧄': ['garlic', 'food'],
    '🧅': ['onion', 'food'],
    '🥔': ['potato', 'food', 'vegetable'],
    '🍠': ['sweet', 'potato', 'food'],
    '🫘': ['beans', 'food'],
    '🥐': ['croissant', 'bread', 'french', 'pastry'],
    '🥖': ['baguette', 'bread', 'french'],
    '🫓': ['flatbread', 'bread'],
    '🍞': ['bread', 'toast', 'food'],
    '🥨': ['pretzel', 'snack'],
    '🥯': ['bagel', 'bread'],
    '🧇': ['waffle', 'breakfast'],
    '🥞': ['pancake', 'breakfast'],
    '🍳': ['egg', 'fry', 'breakfast', 'cooking'],
    '🥚': ['egg', 'food'],
    '🧀': ['cheese', 'food'],
    '🥩': ['meat', 'steak', 'food'],
    '🥓': ['bacon', 'meat', 'food'],
    '🍔': ['burger', 'hamburger', 'food', 'fast'],
    '🍟': ['fries', 'french', 'food', 'fast'],
    '🍕': ['pizza', 'food', 'italian'],
    '🌭': ['hot', 'dog', 'food'],
    '🥪': ['sandwich', 'food'],
    '🌮': ['taco', 'mexican', 'food'],
    '🌯': ['burrito', 'mexican', 'food'],
    '🫔': ['tamale', 'mexican', 'food'],
    '🥙': ['pita', 'falafel', 'food'],
    '🧆': ['falafel', 'food'],
    '🥗': ['salad', 'food', 'healthy'],
    '🍝': ['pasta', 'spaghetti', 'italian', 'food'],
    '🍜': ['noodle', 'ramen', 'soup', 'food', 'asian'],
    '🍲': ['stew', 'pot', 'food', 'soup'],
    '🍛': ['curry', 'rice', 'food', 'indian'],
    '🍣': ['sushi', 'food', 'japanese', 'fish'],
    '🍱': ['bento', 'box', 'food', 'japanese'],
    '🥟': ['dumpling', 'food', 'asian'],
    '🦪': ['oyster', 'seafood'],
    '🍤': ['shrimp', 'prawn', 'seafood', 'food'],
    '🍙': ['rice', 'ball', 'food', 'japanese'],
    '🍚': ['rice', 'food'],
    '🍘': ['rice', 'cracker', 'food', 'japanese'],
    '🍥': ['fish', 'cake', 'food', 'japanese'],
    '🥠': ['fortune', 'cookie', 'food'],
    '🥮': ['moon', 'cake', 'food'],
    '🍡': ['dango', 'food', 'japanese', 'sweet'],
    '🥧': ['pie', 'food', 'dessert'],
    '🍰': ['cake', 'dessert', 'sweet', 'food'],
    '🎂': ['birthday', 'cake', 'celebration', 'party'],
    '🍮': ['pudding', 'custard', 'dessert'],
    '🍭': ['lollipop', 'candy', 'sweet'],
    '🍬': ['candy', 'sweet'],
    '🍫': ['chocolate', 'candy', 'sweet'],
    '🍿': ['popcorn', 'movie', 'snack'],
    '🍩': ['donut', 'doughnut', 'sweet'],
    '🍪': ['cookie', 'sweet', 'food'],
    '☕': ['coffee', 'tea', 'hot', 'drink', 'cafe'],
    '🍵': ['tea', 'green', 'drink', 'hot'],
    '🫖': ['teapot', 'tea', 'drink'],
    '🧋': ['boba', 'bubble', 'tea', 'drink'],
    '🥤': ['drink', 'cup', 'soda', 'juice'],
    '🍺': ['beer', 'drink', 'alcohol'],
    // Activities
    '⚽': ['soccer', 'football', 'ball', 'sport'],
    '🏀': ['basketball', 'ball', 'sport'],
    '🏈': ['football', 'american', 'sport'],
    '⚾': ['baseball', 'ball', 'sport'],
    '🥎': ['softball', 'ball', 'sport'],
    '🎾': ['tennis', 'ball', 'sport'],
    '🏐': ['volleyball', 'ball', 'sport'],
    '🏉': ['rugby', 'ball', 'sport'],
    '🥏': ['frisbee', 'disc', 'sport'],
    '🎱': ['billiards', 'pool', 'ball', 'eight'],
    '🪀': ['yoyo', 'toy'],
    '🏓': ['ping', 'pong', 'table', 'tennis'],
    '🏸': ['badminton', 'sport'],
    '🏒': ['hockey', 'ice', 'sport'],
    '🏑': ['hockey', 'field', 'sport'],
    '🥍': ['lacrosse', 'sport'],
    '🏏': ['cricket', 'sport'],
    '🪃': ['boomerang'],
    '🥅': ['goal', 'net', 'sport'],
    '⛳': ['golf', 'flag', 'sport'],
    '🪁': ['kite', 'fly'],
    '🏹': ['bow', 'arrow', 'archery'],
    '🎣': ['fishing', 'rod', 'fish'],
    '🤿': ['dive', 'diving', 'scuba', 'snorkel'],
    '🥊': ['boxing', 'glove', 'fight', 'sport'],
    '🥋': ['martial', 'arts', 'karate', 'judo'],
    '🎽': ['running', 'shirt', 'sport'],
    '🛹': ['skateboard', 'skate'],
    '🛼': ['roller', 'skate'],
    '🛷': ['sled', 'winter'],
    '⛸️': ['ice', 'skate', 'winter'],
    '🥌': ['curling', 'sport'],
    '🎿': ['ski', 'winter', 'snow'],
    '⛷️': ['ski', 'skier', 'winter'],
    '🏂': ['snowboard', 'winter', 'snow'],
    '🪂': ['parachute', 'skydive'],
    '🏋️': ['weight', 'lift', 'gym', 'strong'],
    '🤸': ['cartwheel', 'gymnastics'],
    '🤺': ['fencing', 'sword', 'sport'],
    '⛹️': ['basketball', 'bounce', 'sport'],
    '🤾': ['handball', 'sport'],
    '🏌️': ['golf', 'sport'],
    '🏇': ['horse', 'racing', 'jockey'],
    '🧘': ['yoga', 'meditation', 'zen', 'relax'],
    '🏄': ['surf', 'surfing', 'wave'],
    '🏊': ['swim', 'swimming', 'pool'],
    '🤽': ['water', 'polo', 'sport'],
    '🚣': ['rowing', 'boat'],
    '🧗': ['climb', 'climbing', 'rock'],
    '🚴': ['bike', 'cycling', 'bicycle'],
    '🏆': ['trophy', 'winner', 'champion', 'award', 'prize'],
    '🥇': ['gold', 'medal', 'first', 'winner'],
    '🥈': ['silver', 'medal', 'second'],
    '🥉': ['bronze', 'medal', 'third'],
    '🏅': ['medal', 'sport', 'award'],
    '🎖️': ['medal', 'military', 'award'],
    '🏵️': ['rosette', 'award'],
    '🎗️': ['ribbon', 'awareness'],
    '🎪': ['circus', 'tent', 'show'],
    '🎭': ['theater', 'theatre', 'drama', 'mask', 'arts'],
    '🎨': ['art', 'paint', 'palette', 'color', 'creative'],
    '🎬': ['movie', 'film', 'cinema', 'action'],
    '🎤': ['microphone', 'sing', 'karaoke', 'music'],
    '🎧': ['headphones', 'music', 'listen', 'audio'],
    '🎼': ['music', 'score', 'notes'],
    '🎹': ['piano', 'keyboard', 'music'],
    '🥁': ['drum', 'music'],
    '🪘': ['drum', 'music'],
    '🎷': ['saxophone', 'jazz', 'music'],
    '🎺': ['trumpet', 'music'],
    '🪗': ['accordion', 'music'],
    '🎸': ['guitar', 'rock', 'music'],
    '🎻': ['violin', 'music', 'classical'],
    '🪕': ['banjo', 'music'],
    '🎲': ['dice', 'game', 'luck', 'random'],
    '♟️': ['chess', 'game', 'strategy'],
    '🎯': ['target', 'dart', 'bullseye', 'goal'],
    '🎳': ['bowling', 'sport', 'game'],
    '🎮': ['game', 'controller', 'video', 'play', 'gaming'],
    '🕹️': ['joystick', 'game', 'arcade'],
    // Travel
    '🚗': ['car', 'vehicle', 'drive', 'red'],
    '🚕': ['taxi', 'cab', 'car', 'vehicle'],
    '🚙': ['car', 'suv', 'vehicle'],
    '🚌': ['bus', 'vehicle', 'transport'],
    '🚎': ['trolleybus', 'bus', 'vehicle'],
    '🏎️': ['racing', 'car', 'fast', 'formula'],
    '🚓': ['police', 'car', 'vehicle'],
    '🚑': ['ambulance', 'hospital', 'emergency'],
    '🚒': ['fire', 'truck', 'engine', 'emergency'],
    '🚐': ['minibus', 'van', 'vehicle'],
    '🛻': ['pickup', 'truck', 'vehicle'],
    '🚚': ['truck', 'delivery', 'vehicle'],
    '🚛': ['truck', 'semi', 'vehicle'],
    '🚜': ['tractor', 'farm', 'vehicle'],
    '🛵': ['scooter', 'vespa', 'vehicle'],
    '🏍️': ['motorcycle', 'bike', 'vehicle'],
    '🛺': ['rickshaw', 'vehicle'],
    '🚲': ['bicycle', 'bike', 'cycle'],
    '🛴': ['scooter', 'kick'],
    '🚏': ['bus', 'stop'],
    '🛣️': ['road', 'highway', 'motorway'],
    '🛤️': ['railway', 'train', 'track'],
    '⛽': ['fuel', 'gas', 'petrol', 'station'],
    '🛞': ['wheel', 'tire'],
    '🚨': ['siren', 'police', 'emergency', 'light'],
    '🚥': ['traffic', 'light', 'signal'],
    '🚦': ['traffic', 'light', 'signal'],
    '🚧': ['construction', 'barrier', 'work'],
    '⚓': ['anchor', 'ship', 'boat', 'sea'],
    '🛟': ['life', 'ring', 'buoy', 'rescue'],
    '⛵': ['sailboat', 'boat', 'sea', 'ship'],
    '🚤': ['speedboat', 'boat', 'fast'],
    '🛳️': ['cruise', 'ship', 'boat'],
    '⛴️': ['ferry', 'boat', 'ship'],
    '🛥️': ['boat', 'motorboat'],
    '🚢': ['ship', 'boat', 'cruise'],
    '✈️': ['airplane', 'plane', 'flight', 'travel'],
    '🛩️': ['airplane', 'small', 'plane'],
    '🛫': ['takeoff', 'plane', 'departure'],
    '🛬': ['landing', 'plane', 'arrival'],
    '💺': ['seat', 'plane', 'chair'],
    '🚁': ['helicopter', 'fly'],
    '🚟': ['monorail', 'train'],
    '🚠': ['cable', 'car', 'mountain'],
    '🚡': ['gondola', 'cable', 'car'],
    '🛰️': ['satellite', 'space'],
    '🚀': ['rocket', 'space', 'launch', 'fast'],
    '🛸': ['ufo', 'alien', 'flying', 'saucer'],
    '🌍': ['earth', 'globe', 'world', 'europe', 'africa'],
    '🌎': ['earth', 'globe', 'world', 'americas'],
    '🌏': ['earth', 'globe', 'world', 'asia'],
    '🗺️': ['map', 'world'],
    '🧭': ['compass', 'navigation', 'direction'],
    '🏔️': ['mountain', 'snow', 'peak'],
    '⛰️': ['mountain'],
    '🌋': ['volcano', 'mountain', 'eruption'],
    '🗻': ['fuji', 'mountain', 'japan'],
    '🏕️': ['camping', 'tent', 'nature'],
    '🏖️': ['beach', 'umbrella', 'summer', 'vacation'],
    '🏜️': ['desert', 'sand'],
    '🏝️': ['island', 'tropical', 'palm'],
    '🏞️': ['park', 'nature', 'landscape'],
    '🏟️': ['stadium', 'sport'],
    '🏛️': ['building', 'classical', 'museum'],
    '🏗️': ['construction', 'building', 'crane'],
    '🧱': ['brick', 'wall', 'building'],
    '🪨': ['rock', 'stone'],
    '🪵': ['wood', 'log'],
    '🛖': ['hut', 'house'],
    '🏠': ['house', 'home'],
    '🏡': ['house', 'home', 'garden'],
    '🏢': ['building', 'office'],
    '🏣': ['post', 'office', 'japanese'],
    '🏤': ['post', 'office'],
    '🏥': ['hospital', 'medical'],
    '🏦': ['bank', 'money', 'building'],
    '🏨': ['hotel', 'building'],
    '🏩': ['hotel', 'love'],
    '🏪': ['store', 'shop', 'convenience'],
    // Objects
    '💡': ['bulb', 'light', 'idea', 'bright'],
    '🔦': ['flashlight', 'torch', 'light'],
    '🕯️': ['candle', 'light', 'flame'],
    '📚': ['books', 'library', 'read', 'study', 'education'],
    '📖': ['book', 'open', 'read'],
    '📝': ['note', 'memo', 'write', 'pencil'],
    '✏️': ['pencil', 'write', 'edit'],
    '🖊️': ['pen', 'write'],
    '🖋️': ['fountain', 'pen', 'write'],
    '📌': ['pin', 'pushpin', 'location'],
    '📎': ['paperclip', 'clip', 'attachment'],
    '🔗': ['link', 'chain', 'url'],
    '📐': ['ruler', 'triangle', 'math'],
    '📏': ['ruler', 'straight', 'measure'],
    '🗂️': ['dividers', 'folder', 'organize'],
    '📁': ['folder', 'file', 'directory'],
    '📂': ['folder', 'open', 'file'],
    '🗃️': ['card', 'file', 'box'],
    '📦': ['package', 'box', 'delivery'],
    '📫': ['mailbox', 'mail', 'post'],
    '📮': ['postbox', 'mail'],
    '📯': ['horn', 'postal'],
    '📰': ['newspaper', 'news', 'press'],
    '🗞️': ['newspaper', 'roll', 'news'],
    '💰': ['money', 'bag', 'dollar', 'rich'],
    '💳': ['card', 'credit', 'payment', 'bank'],
    '💎': ['gem', 'diamond', 'jewel', 'precious'],
    '⚖️': ['scale', 'balance', 'justice', 'law'],
    '🪜': ['ladder', 'climb'],
    '🧰': ['toolbox', 'tools'],
    '🪛': ['screwdriver', 'tool'],
    '🔧': ['wrench', 'tool', 'fix', 'repair'],
    '🔨': ['hammer', 'tool', 'build'],
    '⚒️': ['hammer', 'pick', 'tool'],
    '🛠️': ['tools', 'hammer', 'wrench'],
    '⛏️': ['pick', 'mining', 'tool'],
    '🪚': ['saw', 'tool', 'wood'],
    '🔩': ['nut', 'bolt', 'screw'],
    '⚙️': ['gear', 'settings', 'cog', 'mechanical'],
    '🪤': ['trap', 'mouse'],
    '🧲': ['magnet', 'attract'],
    '🔫': ['gun', 'water', 'pistol'],
    '💣': ['bomb', 'explode'],
    '🪓': ['axe', 'tool', 'chop'],
    '🗡️': ['dagger', 'knife', 'sword'],
    '⚔️': ['swords', 'crossed', 'battle'],
    '🛡️': ['shield', 'protect', 'defense'],
    '🔮': ['crystal', 'ball', 'magic', 'fortune'],
    '🪄': ['magic', 'wand'],
    '🎩': ['hat', 'top', 'magic', 'formal'],
    '📱': ['phone', 'mobile', 'smartphone', 'cell'],
    '💻': ['laptop', 'computer', 'mac', 'pc'],
    '⌨️': ['keyboard', 'type', 'computer'],
    '🖥️': ['desktop', 'computer', 'monitor', 'screen'],
    '🖨️': ['printer', 'print'],
    '🖱️': ['mouse', 'computer', 'click'],
    '💾': ['floppy', 'disk', 'save'],
    '💿': ['cd', 'disc', 'dvd'],
    '📀': ['dvd', 'disc'],
    '🎥': ['camera', 'movie', 'film', 'video'],
    '📷': ['camera', 'photo', 'picture'],
    '📸': ['camera', 'flash', 'photo'],
    '📹': ['video', 'camera', 'camcorder'],
    '📺': ['tv', 'television', 'screen', 'monitor'],
    '📻': ['radio', 'music'],
    '🎙️': ['microphone', 'studio', 'podcast'],
    '🎚️': ['slider', 'level', 'volume'],
    '🎛️': ['knobs', 'control', 'dial'],
    '⏱️': ['stopwatch', 'timer', 'time'],
    '⏰': ['alarm', 'clock', 'time', 'wake'],
    '🔑': ['key', 'lock', 'password'],
    '🗝️': ['key', 'old', 'vintage'],
    '🔒': ['lock', 'secure', 'closed'],
    '🔓': ['unlock', 'open'],
    '❤️': ['heart', 'love', 'red'],
    '🧡': ['heart', 'love', 'orange'],
    '💛': ['heart', 'love', 'yellow'],
    '💚': ['heart', 'love', 'green'],
    '💙': ['heart', 'love', 'blue'],
    '💜': ['heart', 'love', 'purple'],
    // Symbols
    '⭐': ['star', 'favorite', 'rating'],
    '🌟': ['star', 'glow', 'shine'],
    '✨': ['sparkle', 'star', 'magic', 'clean', 'new'],
    '💫': ['dizzy', 'star', 'shooting'],
    '🔥': ['fire', 'hot', 'flame', 'lit'],
    '💥': ['boom', 'explosion', 'crash', 'bang'],
    '⚡': ['lightning', 'bolt', 'electric', 'energy', 'fast', 'power'],
    '🌈': ['rainbow', 'color', 'pride'],
    '☀️': ['sun', 'sunny', 'bright', 'weather'],
    '🌤️': ['sun', 'cloud', 'weather'],
    '⛅': ['cloud', 'sun', 'weather'],
    '🌥️': ['cloud', 'sun', 'weather'],
    '🌦️': ['rain', 'sun', 'weather'],
    '🌧️': ['rain', 'cloud', 'weather'],
    '⛈️': ['storm', 'thunder', 'lightning', 'weather'],
    '🌩️': ['lightning', 'cloud', 'weather'],
    '🌪️': ['tornado', 'storm', 'weather'],
    '🌫️': ['fog', 'mist', 'weather'],
    '🌊': ['wave', 'ocean', 'sea', 'water'],
    '💧': ['water', 'drop', 'sweat'],
    '❄️': ['snow', 'ice', 'cold', 'winter', 'frozen'],
    '☃️': ['snowman', 'snow', 'winter'],
    '⛄': ['snowman', 'snow', 'winter'],
    '🎄': ['christmas', 'tree', 'holiday', 'xmas'],
    '🎆': ['fireworks', 'celebration', 'new', 'year'],
    '🎇': ['sparkler', 'fireworks', 'celebration'],
    '🧨': ['firecracker', 'dynamite', 'celebration'],
    '🎈': ['balloon', 'party', 'birthday'],
    '🎉': ['party', 'celebrate', 'tada', 'confetti'],
    '🎊': ['confetti', 'party', 'celebrate'],
    '🎋': ['tanabata', 'tree', 'japanese'],
    '🎍': ['bamboo', 'pine', 'japanese', 'new', 'year'],
    '🎎': ['dolls', 'japanese', 'festival'],
    '🎏': ['carp', 'streamer', 'japanese'],
    '🎐': ['wind', 'chime', 'japanese'],
    '🎑': ['moon', 'ceremony', 'japanese'],
    '🧧': ['red', 'envelope', 'lucky', 'chinese'],
    '🎀': ['ribbon', 'bow', 'gift', 'pink'],
    '🎁': ['gift', 'present', 'birthday', 'christmas'],
    '🎗️': ['ribbon', 'awareness'],
    '✅': ['check', 'done', 'yes', 'correct', 'complete'],
    '❌': ['cross', 'no', 'wrong', 'delete', 'cancel'],
    '❓': ['question', 'mark', 'help'],
    '❗': ['exclamation', 'mark', 'warning', 'important'],
    '‼️': ['double', 'exclamation', 'bangbang'],
    '⁉️': ['exclamation', 'question'],
    '💯': ['hundred', 'perfect', 'score', 'full'],
    '🔴': ['red', 'circle', 'dot'],
    '🟠': ['orange', 'circle', 'dot'],
    '🟡': ['yellow', 'circle', 'dot'],
    '🟢': ['green', 'circle', 'dot'],
    '🔵': ['blue', 'circle', 'dot'],
    '🟣': ['purple', 'circle', 'dot'],
    '⚫': ['black', 'circle', 'dot'],
    '⚪': ['white', 'circle', 'dot'],
    '🟤': ['brown', 'circle', 'dot'],
    '🔶': ['orange', 'diamond', 'large'],
    '🔷': ['blue', 'diamond', 'large'],
    '🔸': ['orange', 'diamond', 'small'],
    '🔹': ['blue', 'diamond', 'small'],
    '♠️': ['spade', 'card', 'suit'],
    '♥️': ['heart', 'card', 'suit'],
    '♦️': ['diamond', 'card', 'suit'],
    '♣️': ['club', 'card', 'suit'],
    '🃏': ['joker', 'card', 'wild'],
    '🀄': ['mahjong', 'game', 'tile'],
    '🎴': ['flower', 'card', 'game', 'japanese'],
    '🔇': ['mute', 'speaker', 'silent'],
    '🔈': ['speaker', 'sound', 'low'],
    '🔉': ['speaker', 'sound', 'medium'],
    '🔊': ['speaker', 'sound', 'loud', 'volume'],
    '📢': ['loudspeaker', 'announcement'],
    '📣': ['megaphone', 'cheer'],
    '🔔': ['bell', 'notification', 'alert'],
    '🔕': ['bell', 'silent', 'mute', 'no'],
    '🎵': ['music', 'note', 'sound'],
    '🎶': ['music', 'notes', 'sound', 'melody'],
    '🏴': ['flag', 'black'],
    '🏁': ['flag', 'checkered', 'finish', 'race'],
    '🚩': ['flag', 'red', 'warning', 'triangle'],
  };
}

class _EmojiCategory {
  final String icon;
  final String name;
  final List<String> emojis;
  const _EmojiCategory(this.icon, this.name, this.emojis);
}
