import 'package:supabase_flutter/supabase_flutter.dart';
import '../../contracts/i_card_repository.dart';
import '../../core/errors/app_exception.dart';
import '../../models/flash_card.dart';

/// Supabase implementation of ICardRepository.
///
/// Table: public.cards
/// RLS: all rows are automatically filtered to auth.uid() = user_id.
/// We still pass userId explicitly to match the interface contract
/// and for clarity, but RLS guarantees isolation server-side.
///
/// Column mapping (snake_case DB → camelCase Dart):
///   id               → id
///   user_id          → userId
///   word             → word
///   translation      → translation
///   transcription    → transcription
///   example_sentence → exampleSentence
///   synonyms         → synonyms   (text[])
///   usage_notes      → usageNotes
///   status           → status     (pending/learning/mastered)
///   ease_factor      → easeFactor
///   interval_days    → intervalDays
///   repetitions      → repetitions
///   next_review      → nextReview  (timestamptz ISO-8601)
///   created_at       → createdAt   (timestamptz ISO-8601)
class SupabaseCardRepository implements ICardRepository {
  final SupabaseClient _supabase;
  static const _table = 'cards';

  const SupabaseCardRepository(this._supabase);

  // ── saveCard ──────────────────────────────────────────────────────────────
  /// INSERT a new card. Omits id/created_at — generated by Supabase.
  /// Sets status = 'learning' and next_review = now() per Next.js POST /api/cards.
  @override
  Future<FlashCard> saveCard(FlashCard card) async {
    try {
      final data = await _supabase
          .from(_table)
          .insert({
            'user_id':          card.userId,
            'word':             card.word,
            'translation':      card.translation,
            'transcription':    card.transcription,
            'example_sentence': card.exampleSentence,
            'synonyms':         card.synonyms ?? [],
            'usage_notes':      card.usageNotes,
            'status':           'learning',
            'next_review':      DateTime.now().toIso8601String(),
            // SM-2 defaults (ease_factor, interval_days, repetitions use DB defaults)
          })
          .select()
          .single();
      return FlashCard.fromJson(data);
    } catch (e) {
      throw DatabaseException('Failed to save card', cause: e);
    }
  }

  // ── getAllCards ───────────────────────────────────────────────────────────
  /// SELECT all cards for [userId], ordered by created_at DESC.
  @override
  Future<List<FlashCard>> getAllCards(String userId) async {
    try {
      final data = await _supabase
          .from(_table)
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);
      return (data as List).map((e) => FlashCard.fromJson(e as Map<String, dynamic>)).toList();
    } catch (e) {
      throw DatabaseException('Failed to fetch cards', cause: e);
    }
  }

  // ── getDueCards ───────────────────────────────────────────────────────────
  /// Cards where next_review <= [now] AND status != 'mastered',
  /// ordered by next_review ASC (most overdue first).
  /// Matches Next.js GET /api/cards?due=true logic.
  @override
  Future<List<FlashCard>> getDueCards(String userId, DateTime now) async {
    try {
      final data = await _supabase
          .from(_table)
          .select()
          .eq('user_id', userId)
          .lte('next_review', now.toIso8601String())
          .neq('status', 'mastered')
          .order('next_review');
      return (data as List).map((e) => FlashCard.fromJson(e as Map<String, dynamic>)).toList();
    } catch (e) {
      throw DatabaseException('Failed to fetch due cards', cause: e);
    }
  }

  // ── updateCard ────────────────────────────────────────────────────────────
  /// UPDATE card — used after review to apply new SM-2 data.
  /// Matches Next.js PATCH /api/cards behavior.
  @override
  Future<FlashCard> updateCard(FlashCard card) async {
    try {
      final data = await _supabase
          .from(_table)
          .update({
            'translation':      card.translation,
            'transcription':    card.transcription,
            'example_sentence': card.exampleSentence,
            'synonyms':         card.synonyms ?? [],
            'usage_notes':      card.usageNotes,
            'status':           card.status.value,
            'ease_factor':      card.easeFactor,
            'interval_days':    card.intervalDays,
            'repetitions':      card.repetitions,
            'next_review':      card.nextReview.toIso8601String(),
          })
          .eq('id', card.id)
          .eq('user_id', card.userId)
          .select()
          .single();
      return FlashCard.fromJson(data);
    } catch (e) {
      throw DatabaseException('Failed to update card', cause: e);
    }
  }

  // ── deleteCard ────────────────────────────────────────────────────────────
  @override
  Future<void> deleteCard(String cardId) async {
    try {
      await _supabase.from(_table).delete().eq('id', cardId);
    } catch (e) {
      throw DatabaseException('Failed to delete card', cause: e);
    }
  }

  // ── searchCards ───────────────────────────────────────────────────────────
  /// Case-insensitive substring search on word + translation columns.
  @override
  Future<List<FlashCard>> searchCards(String userId, String query) async {
    try {
      final all = await getAllCards(userId);
      final q = query.toLowerCase();
      return all.where((c) =>
          c.word.toLowerCase().contains(q) ||
          (c.translation?.toLowerCase().contains(q) ?? false)).toList();
    } catch (e) {
      throw DatabaseException('Search failed', cause: e);
    }
  }

  // ── getCardCount ──────────────────────────────────────────────────────────
  @override
  Future<int> getCardCount(String userId) async {
    try {
      final response = await _supabase
          .from(_table)
          .select('id')
          .eq('user_id', userId)
          .count(CountOption.exact);
      return response.count;
    } catch (e) {
      throw DatabaseException('Failed to count cards', cause: e);
    }
  }

  // ── clearAllCards ─────────────────────────────────────────────────────────
  @override
  Future<void> clearAllCards(String userId) async {
    try {
      await _supabase.from(_table).delete().eq('user_id', userId);
    } catch (e) {
      throw DatabaseException('Failed to clear cards', cause: e);
    }
  }
}
